# Generated by Django 5.1.2 on 2024-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinishPerDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finish_time", models.CharField(max_length=50)),
                ("score", models.CharField(max_length=10)),
                ("spended_time", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("greeting_text", models.TextField()),
                ("max_number", models.IntegerField(default=100)),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
